#!/usr/bin/env bash
#Display numbers from 1-100. Display "FizzBuzz" when the number is a multiple of 3 and 5. Display "Fizz" when the number is multiple of 3. Display "Buzz" when the number is a multiple of 5. Otherwise, display the number in a list format. 
for a in $(seq 1 100);
 do
if [ $((a % 15)) -eq 0 ]; then
	echo "FizzBuzz"
elif [ $((a % 3)) -eq 0 ]; then
	echo "Fizz"
elif [ $((a % 5)) -eq 0 ]; then
	echo "Buzz"
else
	echo "$a"
fi
done
