#!/usr/bin/env bash
#Display the content of the file /etc/passwd using while loop + IFS. 
while IFS=':' read -ra line
do 
 echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3 place is protected by the passcode $f2, more info about the user here: $f5"
done < /etc/passwd
