#!/usr/bin/env bash
#looping using while and if statements, and adding Hi on a new line
i=1
while [ "$i" -le 10 ]
do
        echo "Best School"
if [ "$i" -eq 9 ];
then 
	echo "Hi"
fi
(( i++ ))
done   
